//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateToGraphVSIX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateToGraphVSIX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Appointment.Accept
        ///$.ajax({
        ///    url: &quot;https://graph.microsoft.com/v1.0/me/events/{id}/accept&quot;,
        ///    method: &quot;POST&quot;,
        ///    headers: {
        ///        &apos;Authorization&apos;: &apos;Bearer {Token}&apos;,
        ///        &quot;Content-Type&quot;: &quot;application/json&quot;,
        ///    },
        ///    data: {
        ///        &quot;comment&quot;: &quot;comment-value&quot;,
        ///        &quot;sendResponse&quot;: true
        ///    },
        ///    success: function (res) {
        ///        console.log(res);
        ///    },
        ///    error: function (res) {
        ///        console.error(res);
        ///    }
        ///})
        /////Appointment.AcceptTentatively
        ///$.ajax({
        ///    url: &quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string api {
            get {
                return ResourceManager.GetString("api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var graph_api_list =
        ///    {
        ///        //get a user https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_get
        ///        &apos;GETAUSER&apos;: {
        ///            api_name: &apos;Get a user&apos;,
        ///            api_url: &apos;https://graph.microsoft.com/v1.0/users/{id | userPrincipalName}&apos;,
        ///            method: &apos;GET&apos;,
        ///            request: {
        ///                request_header: {
        ///                    &apos;Authorization&apos;: &apos;Bearer &apos; + window.sessionStorage.token,
        ///                    &quot;Content-Type&quot;: &quot;application/json&quot;,
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string graph_api_list {
            get {
                return ResourceManager.GetString("graph_api_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UpdateToGraph {
            get {
                object obj = ResourceManager.GetObject("UpdateToGraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
